# Generated by Django 5.0.6 on 2024-05-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicdetails',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
