# Generated by Django 5.0.6 on 2024-05-29 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileapp', '0003_basicdetails_age_basicdetails_body_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='familydetails',
            name='about_family',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='family_location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='family_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='family_value',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='no_of_brothers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='no_of_brothers_married',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='no_of_sisters',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='familydetails',
            name='no_of_sisters_married',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='ancesters_origin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='city',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='locationdetails',
            name='work_place',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='professionalsdetails',
            name='college',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professionalsdetails',
            name='education_in_details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='professionalsdetails',
            name='highest_education',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professionalsdetails',
            name='occupation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='professionalsdetails',
            name='organization',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='religioninformation',
            name='place_of_birth',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='religioninformation',
            name='time_of_birth',
            field=models.TimeField(null=True),
        ),
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(null=True, upload_to='user_gallary')),
                ('image2', models.ImageField(null=True, upload_to='user_gallary')),
                ('image3', models.ImageField(null=True, upload_to='user_gallary')),
                ('image4', models.ImageField(null=True, upload_to='user_gallary')),
                ('image5', models.ImageField(null=True, upload_to='user_gallary')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
