# Generated by Django 5.0.6 on 2024-05-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfileapp', '0006_alter_gallary_image1_alter_gallary_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='religioninformation',
            name='time_of_birth',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
