version: '3.9'

services:
  web:
    build: .
    command: ["gunicorn", "-b", "0.0.0.0:8000", "backend.wsgi:application"]
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend-network

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - backend-network

  celery-beat:
    build: .
    command: ["celery", "-A", "backend", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend-network

  celery-worker:
    build: .
    command: ["celery", "-A", "backend", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend-network

  nginx:
      image: nginx:latest
      volumes:
       - ./nginx-config/nginxconfiguration:/etc/nginx/conf.d/nginxconfiguration
        # - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount letsencrypt if needed
      ports:
        - "8080:80"
        - "8443:443"
      depends_on:
        - web
      networks:
        - backend-network


volumes:
  db_data:

networks:
  backend-network:
    driver: bridge
