version: '3.9'

services:
  web:
    build: .
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application"]
    volumes:
      - .:/app
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - backend-network

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - backend-network

  celery-beat:
    build: .
    command: ["celery", "-A", "backend", "beat", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend-network

  celery-worker:
    build: .
    command: ["celery", "-A", "backend", "worker", "--loglevel=info"]
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "8080:80"
      - "8443:443"
    depends_on:
      - web


volumes:
  db_data:

networks:
  backend-network:
    driver: bridge
