version: '3.9'

services:
  web:
    build: ./backend
    command: ["daphne", "-b", "0.0.0.0", "-p", "8000", "backend.asgi:application"]
    volumes:
      - ./backend:/app
    expose:
      - "8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./env/.env
    networks:
      - backend-network

  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - backend-network

  celery-beat:
    build: ./backend
    command: ["celery", "-A", "backend", "beat", "--loglevel=info"]
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./env/.env
    networks:
      - backend-network

  celery-worker:
    build: ./backend
    command: ["celery", "-A", "backend", "worker", "--loglevel=info"]
    volumes:
      - ./backend:/app
    depends_on:
      - db
    env_file:
      - ./env/.env
    networks:
      - backend-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - backend-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.config:/etc/nginx/conf.d/default.conf:ro  # Point to nginx.config
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount SSL certificates and configuration
    depends_on:
      - web
    networks:
      - backend-network
volumes:
  db_data:

networks:
  backend-network:
    driver: bridge
