# Generated by Django 5.0.6 on 2024-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='male',
            field=models.BooleanField(null=True),
        ),
    ]
