# Generated by Django 5.0.6 on 2024-06-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_alter_chatmessages_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessages',
            name='receiver',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessages',
            name='sender',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
