# Generated by Django 5.0.6 on 2024-06-24 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_alter_chatmessages_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='thread_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
