# Generated by Django 5.0.6 on 2024-07-07 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='seen',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
