# Generated by Django 5.0.6 on 2024-07-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_notifications_seen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
