# Generated by Django 5.0.6 on 2024-07-07 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_alter_notifications_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='seen',
        ),
    ]
