# Generated by Django 5.0.6 on 2024-06-13 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_subscriptiondetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptiondetails',
            old_name='expiry_data',
            new_name='expiry_date',
        ),
    ]
